/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.kigawa.java-conventions")
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:3.0.6")
    api("net.kigawa.kutil:kutil-unit:4.3.0")
    api(project(":kefis-rest-core"))
    runtimeOnly("org.springframework.boot:spring-boot-devtools:3.0.6")
    testImplementation("junit:junit:3.8.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.6")
}

description = "kefis-server"
