/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "kefis"
include(":kefis-rest-core")
include(":kefis-client-core")
include(":kefis-server")
include(":kefis-core-server")
include(":kefis-rest")
