/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.kigawa.java-conventions")
}

dependencies {
    testImplementation("junit:junit:3.8.1")
}

description = "kefis-rest"
