/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.kigawa.java-conventions")
}

dependencies {
    api("net.kigawa.kutil:kutil-unit:4.3.0")
    api("net.kigawa.kutil:kutil-unit-api:4.3.0")
    testImplementation("junit:junit:3.8.1")
}

description = "kefis-client"
