/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("net.kigawa.java-conventions")
}

dependencies {
    api(project(":kefis-core-server"))
    api(project(":kefis-rest"))
    testImplementation("junit:junit:3.8.1")
}

description = "kefis-server"
